server:
  port: 8082
  servlet:
    context-path: '/ead-course/'
spring:
  application:
    name: course
  datasource:
    url: jdbc:mysql://localhost:3306/ead-course-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true