server:
  port: 8082
  servlet:
    context-path: '/ead-course/'
spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:mysql://localhost:3306/ead-course-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
ead:
  api:
    url:
      authuser: "http://ead-authuser-service/ead-authuser"
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost